$: << '../../../lib/'
require 'pp'
require 'cumulus'

desc "This is just for testing..."
task :default do
  
  scanner = Cumulus::Scanner.new(File.dirname(__FILE__))
  scanner.sweep
  
  builder = Cumulus::Builder.new( :dry_run=>true, :verbose=>true )
  
  builder.execute
  
  #pp Cumulus::Resources.all
  
  # c = Cumulus::Resources.collections(:guid=>'GUID_HERE')
  # 
  # pp c
  # 
  # puts 
  # puts "- - - -- - - - - -- - - - - - - - -"
  # puts 
  # 
  # pp c.attachments
  # 
end